name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # change this if your default branch is called something else

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload site files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Change if your files are inside a subfolder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
